#-------------------------------
# General Site Settings
title: Ekofi ID
logo:  # You can add own logo.
description: Ekofi ID login system


#-------------------------------
# Author Settings
author:
  name: Ekofi ID
  image: 01.jpg
  say-hello: This is <strong>Ekofi ID</strong>
  bio: New generation login system.


#-------------------------------
# Contact links
twitter: https://twitter.com/ekofibilim # Add your Twitter handle
facebook: https://facebook.com/ekofibilim # Add your Facebook handle
instagram: https://instagram.com/ekofibilim # Add your Instagram handle


#-------------------------------
# Comment Section (Disqus)



#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: ekofibilim # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
